# Generated by Django 4.1 on 2022-09-09 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="name here...", max_length=50)),
                (
                    "explanation",
                    models.TextField(default="explanation here...", max_length=500),
                ),
                (
                    "example",
                    models.TextField(default="example here...", max_length=500),
                ),
                ("minutesToComplete", models.SmallIntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "whatHeading",
                    models.CharField(default="wHeading here...", max_length=150),
                ),
                (
                    "whatDescription",
                    models.TextField(default="wDescription here...", max_length=500),
                ),
                (
                    "howHeading",
                    models.CharField(default="hHeading here...", max_length=150),
                ),
                (
                    "howDescription",
                    models.TextField(default="hDescription here...", max_length=500),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="name here...", max_length=50)),
                ("intro", models.TextField(default="intro here...", max_length=500)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=50)),
                ("answer", models.BooleanField()),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.content",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="content",
            name="topic",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.topic",
            ),
        ),
    ]
