# Generated by Django 4.1 on 2022-09-03 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='minutesToComplete',
            field=models.SmallIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='content',
            name='example',
            field=models.TextField(default='example here...', max_length=500),
        ),
        migrations.AlterField(
            model_name='content',
            name='explanation',
            field=models.TextField(default='explanation here...', max_length=500),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(default='name here...', max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.topic'),
        ),
        migrations.AlterField(
            model_name='course',
            name='howDescription',
            field=models.TextField(default='hDescription here...', max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='howHeading',
            field=models.CharField(default='hHeading here...', max_length=150),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='whatDescription',
            field=models.TextField(default='wDescription here...', max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='whatHeading',
            field=models.CharField(default='wHeading here...', max_length=150),
        ),
        migrations.AlterField(
            model_name='topic',
            name='intro',
            field=models.TextField(default='intro here...', max_length=500),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(default='name here...', max_length=50),
        ),
    ]
