# Generated by Django 4.1 on 2022-09-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0002_remove_result_enrolment_result_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
