# Generated by Django 4.1 on 2022-09-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment", options={"ordering": ["created_at"]},
        ),
    ]
