# Generated by Django 4.1 on 2022-09-10 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0003_alter_comment_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forum", options={"ordering": ["-created_at"]},
        ),
    ]
